menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}

projects:
- {name: 'Constellation of Truths', description: 'A SSHRC IDG funded project investigating epistemic struggles in contentious border regions.', image: 'assets/img/constellations.jpg', url: 'https://finnsdottir.github.io/constellation-truths/'}
- {name: 'Far-right populism in Canada and Abroad', description: 'A special issue in the Canadian Review of Sociology. Still accepting submissions.', image: 'assets/img/crs_page.jpeg', url: './projects/populism'}

social:
- {icon: 'github', link: 'https://github.com/finnsdottir'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/msfinnsd.bsky.social'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Maria Sigridur Finnsdottir', title: 'Humanities & Social Sciences Specialist', department: 'Digital Research Services-IST', institution: 'University of Alberta', email: 'finnsdot@ualberta.ca', image: 'assets/img/profilepic.jpeg'}
