- title: 'Chair, National Humanities and Social Sciences Team'
  description: 'Digital Research Alliance of Canada (Sep. 2025 – present)'

- title: 'Lead Organizer, [HSS Spotlight Webinar Series](https://explora.alliancecan.ca/events?q=Humanities+and+Social+Sciences+National+Team)'
  description: 'Digital Research Alliance of Canada (Sep. 2025 - Apr. 2026)'

- title: 'Co-organizer, Constellation of Truths: Towards a conceptualization of borders, (un)civil society, and contentious politics'
  description: 'University of Victoria(Apr. 2025)'

- title: 'Co-organizer, Borders, politics, and databases: Using data to power border studies' 
  description: 'Strasbourg, France (Jun. 2024)'

- title: 'UTGSU Course Representative, Graduate Sociology Students Association'
  description: 'University of Toronto (Sep. 2021 - Aug. 2022)'

- title: 'Co-Social Coordinator, Graduate Sociology Students Association'
  description: 'University of Toronto (Sep. 2020 - Aug. 2021)'

- title: 'Vice-President & Treasurer, Graduate Sociology Students Association'
  description: 'University of Toronto (Sep. 2018 - Aug. 2020)'


